# Generated by Django 5.2.7 on 2025-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_income_category_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='tags',
            field=models.ManyToManyField(blank=True, to='finance.tag'),
        ),
    ]
